apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.user_mysql.name }}
  labels:
    app: {{ .Values.user_mysql.name }}
  namespace: {{ .Values.user_mysql.namespace }}
spec:
  replicas: {{ .Values.user_mysql.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.user_mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.user_mysql.name }}
    spec:
      containers:
        - name: {{ .Values.user_mysql.name }}
          image: {{ .Values.user_mysql.statefulset.image }}
          ports:
            - containerPort: {{ .Values.user_mysql.statefulset.container_port }}
          env:
            - name: MYSQL_DATABASE_NAME
              value: {{ .Values.user_mysql.database }}
            - name: MYSQL_USERNAME
              value: {{ .Values.user_mysql.username }}
            - name: MYSQL_USER_PASSWORD
              value: {{ .Values.user_mysql.password }}
