apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.user_service.name }}
  namespace: {{ .Values.user_service.namespace }}
spec:
  replicas: {{ .Values.user_service.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.user_service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.user_service.name }}
    spec:
      containers:
        - name: {{ .Values.user_service.name }}
          image: {{ .Values.user_service.deployment.image }}
          ports:
            - containerPort: {{ .Values.user_service.deployment.container_port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.user_service.deployment.profile }}
            - name: DB_HOST
              value: {{ .Values.user_mysql.name }}
            - name: DB_PORT
              value: "{{ .Values.user_mysql.service.port }}"
            - name: DB_DATABASE
              value: {{ .Values.user_mysql.db_name }}
            - name: DB_USERNAME
              value: {{ .Values.user_mysql.username }}
            - name: DB_PASSWORD
              value: {{ .Values.user_mysql.password }}
