apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.user_mysql.name }}
spec:
  selector:
    app: {{ .Values.user_mysql.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.user_mysql.service.port }}
      targetPort: {{ .Values.user_mysql.statefulset.container_port }}
