apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.user_mysql.name }}
  labels:
    app: {{ .Values.user_mysql.name }}
  namespace: {{ .Values.user_mysql.namespace }}
spec:
  replicas: {{ .Values.user_mysql.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.user_mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.user_mysql.name }}
    spec:
      containers:
        - name: {{ .Values.user_mysql.name }}
          image: {{ .Values.user_mysql.deployment.image }}
          ports:
            - containerPort: {{ .Values.user_mysql.deployment.container_port }}
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.user_mysql.database }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.user_mysql.secret.name }}
                  key: {{ .Values.user_mysql.secret.key }}
