project_name: bokeh
namespace: default
user_service:
  name: user-service
  namespace: default
  gateway:
    uri_prefix: /api/users/
  deployment:
    replicas: 1
    image: public.ecr.aws/a3r8v0w0/bokeh-user_service
    container_port: 8080
    profile: prod
  service:
    port: 8080

user_mysql:
  name: user-mysql
  namespace: default
  statefulset:
    replicas: 1
    image: mysql:8.0.34
    container_port: 3306
  service:
    port: 3306
  db_name: user_db
  username: root
  password: root

user_redis:
  name: user-redis
  namespace: default
  statefulset:
    replicas: 1
    image: redis:7.2.1
    container_port: 6379
  service:
    port: 6379

post_service:
  name: post-service
  namespace: default
  gateway:
    uri_prefix: /api/posts/
  deployment:
    replicas: 1
    image: public.ecr.aws/a3r8v0w0/bokeh-post_service
    container_port: 8080
  service:
    port: 8080

argocd_service:
  name: argocd-server
  namespace: argocd
  gateway:
    uri_prefix: /argocd/
