on: [ push ]

name: Deploy AWS infrastructure

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: AWS Configure
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/aws

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/aws

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/aws
